import type { SolutionPageContent } from "../types";

/** Faithful structural port of `app/(default)/resitve/manipulacija/page.tsx`. */
export const materialHandlingContent: SolutionPageContent = {
  routeKey: "solutionManipulation",
  hero: {
    backLabel: "← Alle Lösungen",
    eyebrow: "Materialhandhabung",
    titleLines: ["Wie ein Werkstück zur nächsten Operation gelangt."],
    subhead:
      "Wir gestalten, wie ein Werkstück gegriffen, bewegt, ausgerichtet und an den nächsten Schritt des Produktionsprozesses übergeben wird.",
    ctas: [{ label: "Materialhandhabung ansehen", anchor: "#manipulacija" }],
    videoSrc: "/video/flexido/hero-logistika.mp4",
  },
  wikiNav: [
    { id: "manipulacija", label: "Materialhandhabung" },
    { id: "naloge", label: "Aufgaben" },
    { id: "zasnova", label: "Gestaltung" },
    { id: "povezane-resitve", label: "Verwandte Lösungen" },
    { id: "tmx", label: "TMX" },
  ],
  sections: [
    {
      type: "numberedSteps",
      id: "manipulacija",
      eyebrow: "Materialhandhabung im Prozess",
      heading: "Das Bewegen des Werkstücks ist Teil der Operation selbst.",
      body: "Manchmal erledigt eine Maschine oder Station ihren Teil der Arbeit, das Werkstück muss danach jedoch korrekt übernommen, ausgerichtet und für den nächsten Schritt vorbereitet werden. Die Materialhandhabung legt fest, wie diese Übergabe erfolgt.",
      steps: [
        { label: "Wo das Werkstück übernommen wird", anchor: "#naloge" },
        { label: "Wie es gegriffen wird", anchor: "#zasnova" },
        { label: "Wie es ausgerichtet sein muss", anchor: "#naloge" },
        { label: "Welchen Weg es zurücklegt", anchor: "#zasnova" },
        { label: "Wo es positioniert wird", anchor: "#naloge" },
        { label: "Wie es weitergegeben wird", anchor: "#naloge" },
      ],
    },
    {
      type: "capabilityGroups",
      id: "naloge",
      eyebrow: "Typische Aufgaben",
      heading: "Klare Schritte rund um eine Maschine oder einen Arbeitsplatz.",
      body: "Wir legen die Lösung anhand des Wegs des Werkstücks unmittelbar bei der Operation fest, unabhängig vom weiteren Transport durch die Produktion.",
      groups: [
        { title: "Übernahme des Werkstücks", body: "Aufnehmen des Werkstücks aus einer Maschine, Station oder vorbereiteten Position." },
        { title: "Ablage", body: "Übergabe des Werkstücks an eine festgelegte Stelle für den nächsten Schritt." },
        { title: "Orientierung und Wenden", body: "Änderung der Lage des Werkstücks vor der weiteren Bearbeitung." },
        { title: "Positionierung", body: "Vorbereitung des Werkstücks in einer festgelegten Lage für Station oder Prozess." },
        { title: "Zuführung", body: "Gezielte Zuführung des Werkstücks in die unmittelbar nachfolgende Operation." },
        { title: "Lokale Übergabe", body: "Übergabe des Werkstücks zwischen zwei direkt verbundenen Prozessschritten." },
      ],
    },
    {
      type: "capabilityGroups",
      id: "zasnova",
      eyebrow: "Lösungsgestaltung",
      heading: "Griff und Bewegung bestimmen den tatsächlichen Prozess.",
      body: "Robotergestützte Materialhandhabung ist erst dann sinnvoll, wenn sie auf Werkstück, Arbeitsplatz und Ablauf der Operation abgestimmt ist.",
      layout: "connectedPath",
      rowSizes: [3, 2],
      groups: [
        { number: "01", title: "Werkstück", body: "Geometrie, Material und erforderliche Ausrichtung." },
        { number: "02", title: "Griff", body: "Wie das Werkstück übernommen und während der Bewegung gehalten wird." },
        { number: "03", title: "Bewegung", body: "Weg, Wenden, Positionierung und Übergabe des Werkstücks." },
        { number: "04", title: "Maschine oder Station", body: "Woher das Werkstück kommt und wohin es als Nächstes muss." },
        { number: "05", title: "Integration", body: "Abfolge, angebundene Ausrüstung und Vision, wenn die Aufgabe Erkennung, Positionierung oder Prüfung erfordert." },
      ],
    },
    {
      type: "relatedSolutions",
      id: "povezane-resitve",
      eyebrow: "Verwandte Lösungen",
      heading: "Wenn Materialhandhabung Teil eines größeren Problems wird.",
      linkLabel: "Lösung ansehen",
      items: [
        { title: "Automatisierung von CNC-Maschinen", body: "Wenn Greifen und Übergeben des Werkstücks untrennbarer Teil der Beschickung einer CNC-Maschine sind.", routeKey: "solutionCnc" },
        { title: "Automatisierung von Spritzgießmaschinen", body: "Wenn Entnahme, Einlegeteile oder Werkstückhandhabung Teil des Spritzgusszyklus sind.", routeKey: "solutionInjectionMolding" },
        { title: "Kollaborative Roboter", body: "Wenn ein Cobot die richtige Technologie für die Handhabungsaufgabe ist.", routeKey: "solutionCobots" },
        { title: "Interne Logistik", body: "Wenn die lokale Übergabe zu einem wiederkehrenden Fluss zwischen Stationen, Behältern oder Produktionsphasen wird.", routeKey: "solutionLogistics" },
      ],
    },
    {
      type: "crossSell",
      id: "tmx",
      eyebrow: "Verwandte Systeme",
      heading: "TMX führt Aufgaben der Materialhandhabung in der Praxis aus.",
      body: "TMX ist eine mobile kollaborative Roboterplattform für Pick & Place, Qualitätskontrolle und einfache Montageaufgaben — eine konkrete Umsetzung der oben beschriebenen Materialhandhabungsaufgaben.",
      right: {
        kind: "image",
        src: "/images/systems/raw/tmx-studio.png",
        alt: "TMX kollaborative Roboterplattform",
        reversed: true,
        size: "feature",
        link: { label: "TMX ansehen", routeKey: "standardCellsTmx" },
      },
    },
  ],
  kontakt: {
    eyebrow: "Kontakt",
    heading: "Wie muss das Werkstück zum nächsten Schritt gelangen?",
    body: "Senden Sie uns grundlegende Informationen zu Werkstück, Geometrie, aktueller Operation, Griff, Bewegung, Ausrichtung und Übergabe an die Maschine oder den Arbeitsplatz.",
    ctaLabel: "Anfrage senden",
    mailto: "info@flexido.eu",
    imageSrc: "/images/systems/raw/flex-25-50-studio-wide.webp",
    imageAlt: "Materialhandhabung in einem Produktionsprozess",
    captionEyebrow: "Erster Schritt",
    captionText: "Wo wird das Werkstück übernommen, ausgerichtet und weitergegeben?",
    variant: "photo",
  },
};
