import type { SolutionPageContent } from "../types";

/** Faithful structural port of `app/(default)/resitve/manipulacija/page.tsx`. */
export const materialHandlingContent: SolutionPageContent = {
  routeKey: "solutionManipulation",
  hero: {
    backLabel: "← All solutions",
    eyebrow: "Material handling",
    titleLines: ["How a part gets to the next operation."],
    subhead:
      "We design how a part is gripped, moved, oriented, and handed off to the next step of the production process.",
    ctas: [{ label: "See material handling", anchor: "#manipulacija" }],
    videoSrc: "/video/flexido/hero-logistika.mp4",
  },
  wikiNav: [
    { id: "manipulacija", label: "Material handling" },
    { id: "naloge", label: "Tasks" },
    { id: "zasnova", label: "Design" },
    { id: "povezane-resitve", label: "Related solutions" },
    { id: "tmx", label: "TMX" },
  ],
  sections: [
    {
      type: "problemSplit",
      id: "manipulacija",
      eyebrow: "Material handling in the process",
      heading: "Moving the part is part of the operation itself.",
      body: [
        "Sometimes a machine or station completes its part of the job, but the part still needs to be correctly picked up, oriented, and prepared for the next step.",
        "Material handling determines how that handoff happens.",
      ],
      itemsEyebrow: "How the handoff happens",
      items: [
        "Where the part is picked up",
        "How it is gripped",
        "How it needs to be oriented",
        "How it is handed off further",
      ],
      result: "Result: moving the part has to be part of the operation itself, not an afterthought.",
    },
    {
      type: "capabilityGroups",
      id: "naloge",
      eyebrow: "Typical tasks",
      heading: "Clear steps around a machine or workstation.",
      body: "We define the solution based on the part's path directly at the operation, not the broader transport across production.",
      groups: [
        { title: "Picking up the part", body: "Picking the part from a machine, station, or prepared location." },
        { title: "Placement", body: "Handing the part off to a defined location for the next step." },
        { title: "Orientation and turning", body: "Changing the part's position ahead of further processing." },
        { title: "Positioning", body: "Preparing the part in a defined position for the station or process." },
        { title: "Feeding", body: "Directed feeding of the part into the immediately following operation." },
        { title: "Local handoff", body: "Transferring the part between two directly connected process steps." },
      ],
    },
    {
      type: "capabilityGroups",
      id: "zasnova",
      eyebrow: "Solution design",
      heading: "Grip and motion define the actual process.",
      body: "Robotic material handling only makes sense once it is aligned with the part, the workstation, and the sequence of the operation.",
      layout: "connectedPath",
      rowSizes: [3, 2],
      groups: [
        { number: "01", title: "Part", body: "Geometry, material, and required orientation." },
        { number: "02", title: "Grip", body: "How the part is picked up and held during movement." },
        { number: "03", title: "Motion", body: "Path, turning, positioning, and handoff of the part." },
        { number: "04", title: "Machine or station", body: "Where the part comes from and where it needs to go next." },
        { number: "05", title: "Integration", body: "Sequence, connected equipment, and vision where the task requires sensing, positioning, or inspection." },
      ],
    },
    {
      type: "relatedSolutions",
      id: "povezane-resitve",
      eyebrow: "Related solutions",
      heading: "When material handling becomes part of a bigger problem.",
      linkLabel: "See the solution",
      items: [
        { title: "CNC machine automation", body: "When gripping and handing off the part is an inseparable part of tending a CNC machine.", routeKey: "solutionCnc" },
        { title: "Injection molding automation", body: "When removal, inserts, or part handling are part of the molding cycle.", routeKey: "solutionInjectionMolding" },
        { title: "Collaborative robots", body: "When a cobot is the right technology for the material-handling task.", routeKey: "solutionCobots" },
        { title: "Internal logistics", body: "When local handoff becomes a recurring flow between stations, containers, or production stages.", routeKey: "solutionLogistics" },
      ],
    },
    {
      type: "crossSell",
      id: "tmx",
      eyebrow: "Related systems",
      heading: "TMX performs material-handling tasks in practice.",
      body: "TMX is a mobile collaborative robot platform for pick and place, quality control, and simple assembly tasks — a concrete implementation of the material-handling tasks described above.",
      right: {
        kind: "image",
        src: "/images/systems/raw/tmx-studio.png",
        alt: "TMX collaborative robot platform",
        reversed: true,
        size: "feature",
        link: { label: "View TMX", routeKey: "standardCellsTmx" },
      },
    },
  ],
  kontakt: {
    eyebrow: "Contact",
    heading: "How does the part need to get to the next step?",
    body: "Send us basic information about the part, its geometry, the current operation, the grip, the motion, the orientation, and the handoff to the machine or workstation.",
    ctaLabel: "Send an inquiry",
    mailto: "info@flexido.eu",
    imageSrc: "/images/systems/raw/flex-25-50-studio-wide.webp",
    imageAlt: "Material handling in a production process",
    captionEyebrow: "First step",
    captionText: "Where is the part picked up, oriented, and handed off further?",
    variant: "photo",
  },
};
