import type { SolutionPageContent } from "../types";

/** Faithful structural port of `app/(default)/resitve/manipulacija/page.tsx`. */
export const materialHandlingContent: SolutionPageContent = {
  routeKey: "solutionManipulation",
  hero: {
    backLabel: "← Vse rešitve",
    eyebrow: "Manipulacija materiala",
    titleLines: ["Kako kos pride do naslednje operacije."],
    subhead:
      "Zasnovali smo, kako se kos prime, premakne, usmeri in preda v naslednji korak proizvodnega procesa.",
    ctas: [{ label: "Poglej manipulacijo", anchor: "#manipulacija" }],
    videoSrc: "/video/flexido/hero-logistika.mp4",
  },
  wikiNav: [
    { id: "manipulacija", label: "Manipulacija" },
    { id: "naloge", label: "Naloge" },
    { id: "zasnova", label: "Zasnova" },
    { id: "povezane-resitve", label: "Povezane rešitve" },
    { id: "tmx", label: "TMX" },
  ],
  sections: [
    {
      type: "problemSplit",
      id: "manipulacija",
      eyebrow: "Manipulacija v procesu",
      heading: "Premik kosa je del same operacije.",
      body: [
        "Včasih stroj ali postaja opravi svoj del, kos pa mora biti nato pravilno prevzet, usmerjen in pripravljen za naslednji korak.",
        "Manipulacija določi, kako se ta predaja izvede.",
      ],
      itemsEyebrow: "Kako poteka predaja",
      items: [
        "Kje se kos prevzame",
        "Kako se ga prime",
        "Kako mora biti usmerjen",
        "Kako se ga preda naprej",
      ],
      result: "predaja kosa mora biti del same operacije, ne dodatek k njej.",
      resultLabel: "Rezultat",
    },
    {
      type: "capabilityGroups",
      id: "naloge",
      eyebrow: "Tipične naloge",
      heading: "Jasni koraki okoli stroja ali delovnega mesta.",
      body: "Rešitev določimo glede na pot kosa neposredno ob operaciji, ne glede na širši transport po proizvodnji.",
      groups: [
        { title: "Prevzem kosa", body: "Pobiranje kosa iz stroja, postaje ali pripravljenega mesta." },
        { title: "Odlaganje", body: "Predaja kosa na določeno mesto za naslednji korak." },
        { title: "Orientacija in obračanje", body: "Sprememba položaja kosa pred nadaljnjo obdelavo." },
        { title: "Pozicioniranje", body: "Priprava kosa v določenem položaju za postajo ali proces." },
        { title: "Dovajanje", body: "Usmerjen dovod kosa v neposredno naslednjo operacijo." },
        { title: "Lokalna predaja", body: "Prenos kosa med neposredno povezanima korakoma procesa." },
      ],
    },
    {
      type: "capabilityGroups",
      id: "zasnova",
      eyebrow: "Zasnova rešitve",
      heading: "Prijem in gib določita dejanski proces.",
      body: "Robotska manipulacija je smiselna šele, ko je usklajena s kosom, delovnim mestom in zaporedjem operacije.",
      layout: "connectedPath",
      rowSizes: [3, 2],
      groups: [
        { number: "01", title: "Kos", body: "Geometrija, material in zahtevana orientacija." },
        { number: "02", title: "Prijem", body: "Kako se kos prevzame in zadrži med premikom." },
        { number: "03", title: "Gib", body: "Pot, obračanje, pozicioniranje in predaja kosa." },
        { number: "04", title: "Stroj ali postaja", body: "Od kod kos pride in kam mora naprej." },
        { number: "05", title: "Integracija", body: "Zaporedje, povezana oprema in vision, kadar zahteva naloga zaznavanje, pozicioniranje ali kontrolo." },
      ],
    },
    {
      type: "relatedSolutions",
      id: "povezane-resitve",
      eyebrow: "Povezane rešitve",
      heading: "Ko manipulacija postane del širšega problema.",
      linkLabel: "Poglej rešitev",
      items: [
        { title: "CNC avtomatizacija", body: "Kadar je prijem in predaja kosa neločljiv del strego CNC stroja.", routeKey: "solutionCnc" },
        { title: "Brizganje plastike", body: "Kadar so odvzem, inserti ali rokovanje s kosi del cikla brizganja.", routeKey: "solutionInjectionMolding" },
        { title: "Kolaborativni roboti", body: "Kadar je cobot primerna tehnologija za nalogo manipulacije.", routeKey: "solutionCobots" },
        { title: "Interna logistika", body: "Kadar lokalna predaja postane ponavljajoč tok med postajami, zabojniki ali proizvodnimi fazami.", routeKey: "solutionLogistics" },
      ],
    },
    {
      type: "crossSell",
      id: "tmx",
      eyebrow: "Povezani sistemi",
      heading: "TMX izvaja naloge manipulacije v praksi.",
      body: "TMX je mobilna kolaborativna robotska platforma za pick and place, kontrolo kakovosti in enostavne montažne naloge — konkretna izvedba nalog manipulacije, opisanih zgoraj.",
      right: {
        kind: "image",
        src: "/images/systems/raw/tmx-studio.png",
        alt: "TMX kolaborativna robotska platforma",
        reversed: true,
        size: "feature",
        link: { label: "Poglej TMX", routeKey: "standardCellsTmx" },
      },
    },
  ],
  kontakt: {
    eyebrow: "Kontakt",
    heading: "Kako mora kos priti do naslednjega koraka?",
    body: "Pošljite nam osnovne informacije o kosu, geometriji, trenutni operaciji, prijemu, gibu, orientaciji in predaji do stroja ali delovnega mesta.",
    ctaLabel: "Pošljite povpraševanje",
    mailto: "info@flexido.eu",
    imageSrc: "/images/systems/raw/flex-25-50-studio-wide.webp",
    imageAlt: "Manipulacija materiala v proizvodnem procesu",
    captionEyebrow: "Prvi korak",
    captionText: "Kje se kos prevzame, usmeri in preda naprej?",
    variant: "photo",
  },
};
