import type { SolutionPageContent } from "../types";

/** German translation of `sl.ts`. Same structure, block-for-block. */
export const injectionMoldingContent: SolutionPageContent = {
  routeKey: "solutionInjectionMolding",
  hero: {
    backLabel: "← Alle Lösungen",
    eyebrow: "Spritzgießen",
    titleLines: ["Spritzgießen,", "nicht nur Teileentnahme."],
    subhead:
      "Wenn der Prozess Einlegeteile, Vorbereitung, Prüfung oder zusätzliche Arbeitsschritte erfordert, gestalten wir die Automatisierung rund um Maschine, Werkzeug und den tatsächlichen Spritzgießablauf.",
    ctas: [{ label: "Standard oder kundenspezifisch", anchor: "#resitev" }],
    videoSrc: "/video/flexido/hero-imm.mp4",
  },
  wikiNav: [
    { id: "brizganje", label: "Spritzgießen" },
    { id: "moznosti", label: "Umsetzungsmöglichkeiten" },
    { id: "resitev", label: "Standard oder kundenspezifisch" },
    { id: "projekt", label: "Projekt" },
  ],
  sections: [
    {
      type: "problemSplit",
      id: "brizganje",
      eyebrow: "Der Spritzgießprozess",
      heading: "Automatisierung kann Teil des gesamten Zyklus sein.",
      body: [
        "Bei anspruchsvolleren Umsetzungen geht es nicht nur um die Entnahme des Spritzgussteils.",
        "Der Prozess kann die Vorbereitung von Einlegeteilen, Arbeiten am Werkzeug, Prüfung sowie Arbeitsschritte vor oder nach dem Spritzgießen umfassen.",
      ],
      itemsEyebrow: "Was der Prozess umfassen kann",
      items: [
        "Vorbereitung und Zufuhr von Einlegeteilen",
        "Einlegen ins Werkzeug und Umspritzen",
        "Entnahme, Prüfung und zusätzliche Arbeitsschritte",
        "Anbindung von Maschine, Robotern, Stationen und Prozess",
      ],
      result: "die Automatisierung muss den gesamten Zyklus abdecken, nicht nur die Teileentnahme.",
      resultLabel: "Ergebnis",
    },
    {
      type: "capabilityGroups",
      id: "moznosti",
      eyebrow: "Umsetzungsmöglichkeiten",
      heading: "Wir wählen die Bausteine passend zum Spritzgießprozess.",
      body: "Jede Lösung verbindet die Schritte, die an der konkreten Maschine und dem Werkzeug abgestimmt zusammenwirken müssen.",
      groups: [
        { number: "01", title: "Einlegeteile und Greifarten", body: "Vorbereitung, Handhabung und Einlegen von Einlegeteilen ins Werkzeug — z. B. Motorstator, Bowden-Kabel, Buchsen oder Unterlegscheiben — mit Greifarten, die auf das Teil und den Umspritzprozess abgestimmt sind." },
        { number: "02", title: "Roboter und Vorbereitung", body: "Ein 6-Achs-Roboter bedient typisch die Maschine und legt Einlegeteile ein; ein SCARA-Roboter unterstützt Sortierung und Vorbereitung der Einlegeteile, sofern konfiguriert." },
        { number: "03", title: "Prüfung und Stationen", body: "Bildverarbeitung, Prüfung und Messung sowie zusätzliche Stationen vor oder nach dem Spritzgießen — z. B. Vorwärmen der Einlegeteile, Höhenprüfung unter Last, Oberflächenrändeln und Laser-Schweißen, wenn die Umsetzung dies erfordert." },
        { number: "04", title: "Verbundener Prozess", body: "Anbindung der Spritzgießmaschine, des Roboters, der Stationen und vorhandener Ausrüstung zu einem abgestimmten Arbeitsablauf." },
      ],
    },
    {
      type: "comparisonSplit",
      id: "resitev",
      eyebrow: "Lösungswahl",
      heading: "Standard-Spritzgießzelle oder maßgeschneiderte Automatisierung.",
      body: "Der richtige Weg hängt von Maschine, Werkzeug, Teilen, Einlegeteilen und den erforderlichen Schritten rund um das eigentliche Spritzgießen ab.",
      left: {
        tag: "Standard-Spritzgießzelle",
        title: "Für die wiederkehrende Beschickung der Spritzgießmaschine.",
        body: "FLEX 7 IMM Slim ist eine konfigurierbare Zelle für die Teileentnahme und standardisierte modulare Stationen in einem wiederkehrenden Prozess.",
        link: { label: "Standard-Spritzgießzelle ansehen", routeKey: "standardCellsImm" },
      },
      right: {
        tag: "Maßgeschneiderte Automatisierung des Spritzgießens",
        title: "Für einen Prozess mit mehr als wiederkehrender Entnahme.",
        body: "Die Lösung vereint Einlegeteile, spezielle Greifarten, robotergestütztes Einlegen, zusätzliche Stationen, Prüfung und die Anbindung vorhandener Ausrüstung.",
        link: { label: "Kundenspezifische Systeme ansehen", routeKey: "solutionCustomSystems" },
      },
    },
    {
      type: "crossSell",
      id: "standardna-osnova",
      eyebrow: "Spritzgießen",
      heading: "FLEX 7 IMM Slim",
      body: "Erhältlich mit einem Roboter mit 7 kg oder 10 kg Traglast, passend zur Teilegröße.",
      right: {
        kind: "image",
        src: "/images/systems/raw/flex-7-imm-slim-studio.png",
        alt: "FLEX 7 IMM Slim",
        reversed: true,
        size: "feature",
        link: { label: "FLEX 7 IMM Slim ansehen", routeKey: "standardCellsImm" },
      },
    },
    {
      type: "proofProject",
      id: "projekt",
      eyebrow: "Realisiertes Projekt",
      heading: "Roboterzelle für das Umspritzen.",
      tag: "Automatisierung des Umspritzens",
      title: "Eine Roboterzelle im Spritzgießprozess.",
      body: "Für einen Kunden hat Flexido das Umspritzen von Teilen automatisiert und die erforderliche Stückzahl im Produktionsprozess optimiert.",
      result: "Fast ein Drittel mehr Teile als ursprünglich vorgesehen.",
      image: { src: "/images/systems/raw/robotska-celica-za-nabrizgavanje.png", alt: "Roboterzelle für das Umspritzen" },
      routeKey: "referenceOvermolding",
      readMoreLabel: "Projekt lesen",
      chrome: "open",
      resultTone: "quiet",
    },
  ],
  kontakt: {
    eyebrow: "Kontakt",
    heading: "Werfen wir einen Blick auf Ihren Spritzgießprozess.",
    body: "Senden Sie uns grundlegende Informationen zu Maschine, Werkzeug, Teilen, Einlegeteilen und den erforderlichen zusätzlichen Arbeitsschritten. Gemeinsam prüfen wir, ob eine Standardzelle den Prozess abdeckt oder eine maßgeschneiderte Automatisierung nötig ist.",
    ctaLabel: "Anfrage senden",
    mailto: "info@flexido.eu",
    imageSrc: "/images/systems/raw/flexido-imm-machine-studio.png",
    imageAlt: "Automatisierung des Spritzgießprozesses",
    captionEyebrow: "Erster Schritt",
    captionText: "Wo müssen Maschine, Werkzeug, Einlegeteile und zusätzliche Arbeitsschritte zu einem Prozess zusammenkommen?",
    variant: "photo",
  },
};
