import type { SolutionPageContent } from "../types";

/** English translation of `sl.ts`. Same structure, block-for-block. */
export const injectionMoldingContent: SolutionPageContent = {
  routeKey: "solutionInjectionMolding",
  hero: {
    backLabel: "← All solutions",
    eyebrow: "Injection molding",
    titleLines: ["Injection molding,", "not just part removal."],
    subhead:
      "When the process requires inserts, preparation, inspection, or additional operations, we design automation around the machine, the mold, and the actual molding workflow.",
    ctas: [{ label: "Standard or custom", anchor: "#resitev" }],
    videoSrc: "/video/flexido/hero-imm.mp4",
  },
  wikiNav: [
    { id: "brizganje", label: "Injection molding" },
    { id: "moznosti", label: "Implementation options" },
    { id: "resitev", label: "Standard or custom" },
    { id: "projekt", label: "Project" },
  ],
  sections: [
    {
      type: "problemSplit",
      id: "brizganje",
      eyebrow: "The molding process",
      heading: "Automation can be part of the entire cycle.",
      body: [
        "In more demanding implementations, it isn't just about removing the molded part.",
        "The process can include insert preparation, work at the mold, inspection, and operations before or after molding.",
      ],
      itemsEyebrow: "What the process can include",
      items: [
        "Insert preparation and feeding",
        "Insertion into the mold and overmolding",
        "Removal, inspection, and additional operations",
        "Integration of the machine, robots, stations, and process",
      ],
      result: "automation has to cover the whole cycle, not just part removal.",
      resultLabel: "Result",
    },
    {
      type: "capabilityGroups",
      id: "moznosti",
      eyebrow: "Implementation options",
      heading: "We choose the building blocks based on the molding process.",
      body: "Each solution connects the steps that need to work together around the specific machine and mold.",
      groups: [
        { number: "01", title: "Inserts and grips", body: "Preparation, handling, and insertion of inserts into the mold — e.g. electric motor stators, Bowden cables, bushings, or washers — with grips adapted to the part and the overmolding process." },
        { number: "02", title: "Robot and preparation", body: "A 6-axis robot typically handles machine tending and insert placement; a SCARA robot supports insert sorting and preparation where configured." },
        { number: "03", title: "Inspection and stations", body: "Vision, inspection, and measurement, plus additional stations before or after molding — e.g. insert preheating, height-under-load check, surface knurling, and laser welding when the implementation requires it." },
        { number: "04", title: "Connected process", body: "Integration of the injection molding machine, the robot, stations, and existing equipment into a coordinated workflow." },
      ],
    },
    {
      type: "comparisonSplit",
      id: "resitev",
      eyebrow: "Choosing a solution",
      heading: "Standard IMM cell or tailored automation.",
      body: "The right path depends on the machine, mold, parts, inserts, and the steps needed around the molding itself.",
      left: {
        tag: "Standard IMM cell",
        title: "For repeatable tending of the injection molding machine.",
        body: "FLEX 7 IMM Slim is a configurable cell for part removal and standard modular stations in a repeatable process.",
        link: { label: "See the standard IMM cell", routeKey: "standardCellsImm" },
      },
      right: {
        tag: "Tailored injection molding automation",
        title: "For a process that needs more than repeatable removal.",
        body: "The solution combines inserts, special grips, robotic insertion, additional stations, inspection, and integration with existing equipment.",
        link: { label: "See custom-built systems", routeKey: "solutionCustomSystems" },
      },
    },
    {
      type: "crossSell",
      id: "standardna-osnova",
      eyebrow: "Injection molding",
      heading: "FLEX 7 IMM Slim",
      body: "Available with a 7 kg or 10 kg robot, matched to part size.",
      right: {
        kind: "image",
        src: "/images/systems/raw/flex-7-imm-slim-studio.png",
        alt: "FLEX 7 IMM Slim",
        reversed: true,
        size: "feature",
        link: { label: "See FLEX 7 IMM Slim", routeKey: "standardCellsImm" },
      },
    },
    {
      type: "proofProject",
      id: "projekt",
      eyebrow: "Completed project",
      heading: "Robotic overmolding cell.",
      tag: "Overmolding automation",
      title: "A robotic cell in the molding process.",
      body: "For a customer, Flexido automated the overmolding of parts and optimized the required output quantity in the production process.",
      result: "Almost a third more parts than originally planned.",
      image: { src: "/images/systems/raw/robotska-celica-za-nabrizgavanje.png", alt: "Robotic overmolding cell" },
      routeKey: "referenceOvermolding",
      readMoreLabel: "Read the project",
      chrome: "open",
      resultTone: "quiet",
    },
  ],
  kontakt: {
    eyebrow: "Contact",
    heading: "Let's look at your molding process.",
    body: "Send us the basic information about the machine, mold, parts, inserts, and any additional operations needed. Together we'll assess whether a standard cell covers the process or it needs tailored automation.",
    ctaLabel: "Send an inquiry",
    mailto: "info@flexido.eu",
    imageSrc: "/images/systems/raw/flexido-imm-machine-studio.png",
    imageAlt: "Automation of the injection molding process",
    captionEyebrow: "First step",
    captionText: "Where do the machine, mold, inserts, and additional operations need to come together into a single process?",
    variant: "photo",
  },
};
