import type { SolutionPageContent } from "../types";

/** Faithful structural port of `app/(default)/resitve/brizganje-plastike/page.tsx`. */
export const injectionMoldingContent: SolutionPageContent = {
  routeKey: "solutionInjectionMolding",
  hero: {
    backLabel: "← Vse rešitve",
    eyebrow: "Brizganje plastike",
    titleLines: ["Brizganje,", "ne le odvzem kosov."],
    subhead:
      "Kadar proces zahteva inserte, pripravo, kontrolo ali dodatne operacije, avtomatizacijo zasnujemo okoli stroja, orodja in dejanskega poteka brizganja.",
    ctas: [{ label: "Standardno ali namensko", anchor: "#resitev" }],
    videoSrc: "/video/flexido/hero-imm.mp4",
  },
  wikiNav: [
    { id: "brizganje", label: "Brizganje" },
    { id: "moznosti", label: "Možnosti izvedbe" },
    { id: "resitev", label: "Standardno ali namensko" },
    { id: "projekt", label: "Projekt" },
  ],
  sections: [
    {
      type: "problemSplit",
      id: "brizganje",
      eyebrow: "Proces brizganja",
      heading: "Avtomatizacija je lahko del celotnega cikla.",
      body: [
        "Pri zahtevnejših izvedbah ne gre le za odvzem brizganega kosa.",
        "Proces lahko vključuje pripravo insertov, delo ob orodju, kontrolo in operacije pred ali po brizganju.",
      ],
      itemsEyebrow: "Kaj lahko vključuje proces",
      items: [
        "Priprava in dovod insertov",
        "Vstavljanje v orodje in nabrizgavanje",
        "Odvzem, kontrola in dodatne operacije",
        "Povezava stroja, robotov, postaj in procesa",
      ],
      result: "avtomatizacija mora pokriti celoten cikel, ne le odvzem kosa.",
      resultLabel: "Rezultat",
    },
    {
      type: "capabilityGroups",
      id: "moznosti",
      eyebrow: "Možnosti izvedbe",
      heading: "Gradnike izberemo glede na proces brizganja.",
      body: "Posamezna rešitev poveže tiste korake, ki morajo delovati usklajeno ob konkretnem stroju in orodju.",
      groups: [
        { number: "01", title: "Inserti in prijemi", body: "Priprava, manipulacija in vstavljanje insertov v orodje — npr. statorjev motorov, Bowden kablov, vtičnic ali podložk — s prijemi, prilagojenimi kosu in procesu nabrizgavanja." },
        { number: "02", title: "Robot in priprava", body: "6-osni robot običajno izvaja posluževanje stroja in vstavljanje insertov; SCARA robot podpira sortiranje in pripravo insertov, kadar je konfiguriran." },
        { number: "03", title: "Kontrola in postaje", body: "Vision, kontrola in meritve ter dodatne postaje pred ali po brizganju — npr. predgretje insertov, kontrola višine pod obremenitvijo, površinsko valjenje in lasersko varjenje, kadar to zahteva izvedba." },
        { number: "04", title: "Povezan proces", body: "Povezava stroja za brizganje, robota, postaj in obstoječe opreme v usklajen potek dela." },
      ],
    },
    {
      type: "comparisonSplit",
      id: "resitev",
      eyebrow: "Izbira rešitve",
      heading: "Standardna IMM celica ali namenska avtomatizacija.",
      body: "Prava pot je odvisna od stroja, orodja, kosov, insertov in potrebnih korakov okoli samega brizganja.",
      left: {
        tag: "Standardna IMM celica",
        title: "Za ponovljivo strego stroja za brizganje.",
        body: "FLEX 7 IMM Slim je konfigurabilna celica za odvzem kosov in standardne modularne postaje v ponovljivem procesu.",
        link: { label: "Poglej standardno IMM celico", routeKey: "standardCellsImm" },
      },
      right: {
        tag: "Namenska avtomatizacija brizganja",
        title: "Za proces z več kot ponovljivim odvzemom.",
        body: "Rešitev združi inserte, posebne prijeme, robotsko vstavljanje, dodatne postaje, kontrolo in povezavo z obstoječo opremo.",
        link: { label: "Poglej namenske sisteme", routeKey: "solutionCustomSystems" },
      },
    },
    {
      type: "crossSell",
      id: "standardna-osnova",
      eyebrow: "Brizganje plastike",
      heading: "FLEX 7 IMM Slim",
      body: "Na voljo z robotom nosilnosti 7 ali 10 kg, prilagojeno velikosti kosa.",
      right: {
        kind: "image",
        src: "/images/systems/raw/flex-7-imm-slim-studio.png",
        alt: "FLEX 7 IMM Slim",
        reversed: true,
        size: "feature",
        link: { label: "Poglej FLEX 7 IMM Slim", routeKey: "standardCellsImm" },
      },
    },
    {
      type: "proofProject",
      id: "projekt",
      eyebrow: "Realizirani projekt",
      heading: "Robotska celica za nabrizgavanje.",
      tag: "Avtomatizacija nabrizgavanja",
      title: "Robotska celica v procesu brizganja.",
      body: "Za naročnika je Flexido avtomatiziral nabrizgavanje kosov in optimiziral zahtevano količino v proizvodnem procesu.",
      result: "Skoraj tretjina več kosov od prvotno predvidene količine.",
      image: { src: "/images/systems/raw/robotska-celica-za-nabrizgavanje.png", alt: "Robotska celica za nabrizgavanje" },
      routeKey: "referenceOvermolding",
      readMoreLabel: "Preberi projekt",
      chrome: "open",
      resultTone: "quiet",
    },
  ],
  kontakt: {
    eyebrow: "Kontakt",
    heading: "Poglejmo vaš proces brizganja.",
    body: "Pošljite nam osnovne informacije o stroju, orodju, kosih, insertih in potrebnih dodatnih operacijah. Skupaj ocenimo, ali proces pokrije standardna celica ali namenska avtomatizacija.",
    ctaLabel: "Pošljite povpraševanje",
    mailto: "info@flexido.eu",
    imageSrc: "/images/systems/raw/flexido-imm-machine-studio.png",
    imageAlt: "Avtomatizacija procesa brizganja plastike",
    captionEyebrow: "Prvi korak",
    captionText: "Kje se morajo stroj, orodje, inserti in dodatne operacije povezati v en proces?",
    variant: "photo",
  },
};
