import type { SolutionPageContent } from "../types";

/** Faithful structural port of `customSystems/sl.ts`. */
export const customSystemsContent: SolutionPageContent = {
  routeKey: "solutionCustomSystems",
  hero: {
    backLabel: "← Alle Lösungen",
    eyebrow: "Kundenspezifischer Systemaufbau",
    titleLines: ["Kundenspezifische Systeme", "für verbundene Abläufe."],
    subhead:
      "Wenn weder eine konfigurierbare Zelle noch ein einzelnes Fachgebiet die gesamte Lösung abbildet, entwickeln wir ein kundenspezifisches System rund um die konkrete Abfolge von Abläufen, Stationen und Umsetzungsbedingungen.",
    ctas: [
      { label: "Wann ein kundenspezifisches System sinnvoll ist", anchor: "#izbira" },
      { label: "Gespräch über die Umsetzung", anchor: "#kontakt" },
    ],
    videoSrc: "/video/flexido/hero-home.mp4",
  },
  wikiNav: [
    { id: "sistem", label: "Kundenspezifisches System" },
    { id: "sestava", label: "Was ihn bestimmt" },
    { id: "izbira", label: "Wann es sinnvoll ist" },
    { id: "podrocja", label: "Verwandte Bereiche" },
    { id: "platforma", label: "Plattform" },
    { id: "projekt", label: "Projekt" },
  ],
  sections: [
    {
      type: "problemSplit",
      id: "sistem",
      eyebrow: "Kundenspezifisches System",
      heading: "Die Lösung geht über eine Zelle oder ein Fachgebiet hinaus.",
      body: [
        "Ein kundenspezifisches System wird selten von einem einzelnen Baustein bestimmt.",
        "Es ergibt sich aus verbundenen Abläufen, kundenspezifischen Stationen und Werkzeugen, Umsetzungsbedingungen und einem abgestimmten Gesamtaufbau.",
      ],
      itemsEyebrow: "Was ihn bestimmt",
      items: [
        "Verbundene Abläufe",
        "Kundenspezifische Stationen und Werkzeuge",
        "Umsetzungsbedingungen",
        "Abgestimmter Aufbau",
      ],
      result: "Ergebnis: das System bestimmt die Kombination aus Abläufen, Stationen und Bedingungen — nicht ein einzelner Baustein.",
    },
    {
      type: "capabilityGroups",
      id: "sestava",
      eyebrow: "Kundenspezifischer Aufbau",
      heading: "Das System wird von dem bestimmt, was zusammen funktionieren muss.",
      body: "Ein kundenspezifisches System ist kein Baukasten aus Katalogbausteinen. Es ist eine einzelne Umsetzung, bei der jedes Teil durch die konkrete Arbeitsabfolge und die gegenseitigen Einschränkungen bestimmt wird.",
      layout: "boxed",
      groups: [
        { title: "Verbundene Abläufe", body: "Eine Abfolge mehrerer Schritte muss als eine abgestimmte Umsetzung funktionieren, nicht als eigenständige Zelle mit einer Erweiterung." },
        { title: "Kundenspezifische Stationen und Werkzeuge", body: "Der Prozess erfordert eine Station, einen Greifer, eine Zuführung oder ein anderes Werkzeug, das für ein konkretes Teil und einen bestimmten Arbeitsablauf ausgelegt ist." },
        { title: "Umsetzungsbedingungen", body: "Die Anordnung, bestehende Anlagen oder Schnittstellen bestimmen die Systemarchitektur bereits von Anfang an." },
        { title: "Abgestimmter Aufbau", body: "Die Elemente müssen zu einem Ganzen verbunden werden, mit einer abgestimmten Abfolge und Übergaben zwischen ihnen." },
      ],
    },
    {
      type: "comparisonSplit",
      id: "izbira",
      eyebrow: "Wahl der Lösung",
      heading: "Es geht um mehr als reine Anpassung.",
      body: "Anpassung allein macht noch kein kundenspezifisches System. Das ist dann sinnvoll, wenn eine bestehende Zelle oder ein einzelnes etabliertes Fachgebiet die gesamte Prozessstruktur nicht mehr abdecken kann.",
      left: {
        tag: "Konfigurierbare Zelle oder Speziallösung",
        title: "Wenn der Kern des Prozesses bereits klar definiert ist.",
        body: "Ausgangspunkt ist eine bestehende Zellenarchitektur oder ein Bereich wie CNC, Spritzguss, Cobots, Materialhandhabung oder Logistik.",
      },
      right: {
        tag: "Kundenspezifisches System",
        title: "Wenn das gesamte System kundenspezifisch aufgebaut werden muss.",
        body: "Die Lösung ergibt sich aus der Kombination verbundener Abläufe, spezieller Stationen oder Werkzeuge, der Anordnung und der Anbindung an bestehende Anlagen.",
      },
    },
    {
      type: "textOnly",
      id: "sestavni-deli",
      eyebrow: "Bestandteile der Umsetzung",
      heading: "Wir verbinden nur das, was die konkrete Umsetzung erfordert.",
      body: "Das kann einen Roboter, einen Greifer, eine kundenspezifische Station, die Zu- oder Abfuhr von Teilen, eine Prüfung und die Anbindung an bestehende Anlagen umfassen. Keines dieser Elemente allein macht ein kundenspezifisches System aus.",
    },
    {
      type: "relatedSolutions",
      id: "podrocja",
      eyebrow: "Verwandte Bereiche",
      heading: "Ein Fachgebiet bleibt ein Fachgebiet.",
      body: "Ein kundenspezifisches System kann Elemente dieser Bereiche verbinden, ersetzt sie aber nicht. Wenn einer von ihnen bereits den Kern des Prozesses beschreibt, ist das der richtige Ausgangspunkt für die Lösung.",
      linkLabel: "Bereich ansehen",
      items: [
        { title: "Automatisierung von CNC-Maschinen", body: "Wenn der Kern der Lösung die Bearbeitung, die Beschickung von CNC-Maschinen und die Ausrüstung drumherum ist.", routeKey: "solutionCnc" },
        { title: "Spritzguss", body: "Wenn die Lösung von der Spritzgießmaschine, dem Werkzeug, den Inserts oder dem Spritzzyklus bestimmt wird.", routeKey: "solutionInjectionMolding" },
        { title: "Kollaborative Roboter", body: "Wenn die zentrale Frage ist, ob ein Cobot die passende Technologie für eine klar definierte Operation ist.", routeKey: "solutionCobots" },
        { title: "Materialhandhabung", body: "Wenn die Aufgabe vor allem im Greifen, Bewegen, Ausrichten oder Übergeben eines Teils besteht.", routeKey: "solutionManipulation" },
        { title: "Interne Logistik", body: "Wenn der Kern der Lösung ein sich wiederholender Fluss von Behältern, Paletten oder Material zwischen den Phasen ist.", routeKey: "solutionLogistics" },
      ],
    },
    {
      type: "crossSell",
      id: "platforma",
      eyebrow: "Möglicher Ausgangspunkt",
      heading: "FLEX 25 / 50 kann eine der Plattformen sein.",
      body: "Bei manchen Umsetzungen ist FLEX 25 / 50 ein konfigurierbarer Ausgangspunkt. Seine Anwendungen, Optionen und technischen Daten sind auf der Seite FLEX 25 / 50 zusammengefasst.",
      right: {
        kind: "image",
        src: "/images/systems/raw/flex-25-50-studio-wide.webp",
        alt: "FLEX 25 / 50 Roboterzelle",
        reversed: true,
        size: "feature",
        link: { label: "FLEX 25 / 50 ansehen", routeKey: "standardCellsFlex2550" },
      },
    },
    {
      type: "proofProject",
      id: "projekt",
      eyebrow: "Realisiertes Projekt",
      heading: "Automatisches Formen und Kleben von Kartons.",
      tag: "Kundenspezifisches System für Verpackung",
      title: "Eine Lösung für einen anspruchsvollen Verpackungsprozess.",
      body: "Die Herstellung der Verpackung war aufgrund unterschiedlicher und unvorhersehbarer Variablen anspruchsvoll, weshalb eine kundenspezifische Lösung für einen stabileren und kontrollierten Arbeitsablauf nötig war.",
      image: { src: "/images/systems/raw/avtomatsko-oblikovanje-in-lepljenje-skatel.png", alt: "Automatisches Formen und Kleben von Kartons" },
      routeKey: "referenceCarton",
      readMoreLabel: "Sehen Sie das kundenspezifische System in der Praxis",
    },
  ],
  kontakt: {
    eyebrow: "Nächster Schritt",
    heading: "Schauen wir uns an, was in Ihrer Umsetzung zusammenwirken muss.",
    body: "Zu Beginn benötigen wir die Abfolge der Abläufe, die vorhandene Ausrüstung, den Platz und die Umsetzungsbedingungen. Anschließend beurteilen wir, ob eine bestehende Lösung den Prozess abdeckt oder ob ein kundenspezifischer Systemaufbau erforderlich ist.",
    ctaLabel: "Anfrage senden",
    mailto: "info@flexido.eu",
    imageSrc: "/images/systems/raw/vhodno-izhodna-tracna-proga.png",
    imageAlt: "Verbundenes System aus mehreren Maschinen und Materialtransport",
    captionEyebrow: "Beginn des Gesprächs",
    captionText: "Welche Abfolge von Abläufen kann eine bestehende Lösung nicht abdecken?",
    variant: "photo",
  },
};
