import type { SolutionPageContent } from "../types";

/** Faithful structural port of `customSystems/sl.ts`. */
export const customSystemsContent: SolutionPageContent = {
  routeKey: "solutionCustomSystems",
  hero: {
    backLabel: "← All solutions",
    eyebrow: "Custom system build",
    titleLines: ["Custom-built systems", "for connected operations."],
    subhead:
      "When neither a configurable cell nor a single specialist area covers the whole solution, we design a custom-built system around the actual sequence of operations, stations, and implementation constraints.",
    ctas: [
      { label: "When a custom-built system makes sense", anchor: "#izbira" },
      { label: "Talk about your implementation", anchor: "#kontakt" },
    ],
    videoSrc: "/video/flexido/hero-home.mp4",
  },
  wikiNav: [
    { id: "sistem", label: "Custom-built system" },
    { id: "sestava", label: "What defines it" },
    { id: "izbira", label: "When it makes sense" },
    { id: "podrocja", label: "Related areas" },
    { id: "platforma", label: "Platform" },
    { id: "projekt", label: "Project" },
  ],
  sections: [
    {
      type: "numberedSteps",
      id: "sistem",
      eyebrow: "Custom-built system",
      heading: "The solution goes beyond one cell or one area.",
      body: "A custom-built system is rarely defined by a single building block. It's shaped by connected operations, custom-built stations and tooling, implementation constraints, and a coordinated overall assembly.",
      steps: [
        { label: "Connected operations", anchor: "#sestava" },
        { label: "Custom-built stations and tooling", anchor: "#sestava" },
        { label: "Implementation constraints", anchor: "#sestava" },
        { label: "Coordinated assembly", anchor: "#sestava" },
      ],
    },
    {
      type: "capabilityGroups",
      id: "sestava",
      eyebrow: "Custom-built assembly",
      heading: "The system is defined by what has to work together.",
      body: "A custom-built system isn't a catalog of building blocks. It's a single build in which each part is defined by the actual sequence of work and by how the parts constrain one another.",
      layout: "boxed",
      groups: [
        { title: "Connected operations", body: "A sequence of multiple steps has to work as one coordinated build, not as a standalone cell with an add-on." },
        { title: "Custom-built stations and tooling", body: "The process requires a station, gripper, feeder, or other tooling designed for a specific part and workflow." },
        { title: "Implementation constraints", body: "Layout, existing equipment, or interfaces shape the system's architecture from the outset." },
        { title: "Coordinated assembly", body: "The elements have to connect into a single whole, with a coordinated sequence and handoffs between them." },
      ],
    },
    {
      type: "comparisonSplit",
      id: "izbira",
      eyebrow: "Choosing a solution",
      heading: "It takes more than customization.",
      body: "Customization on its own doesn't make a custom-built system. That's the right call once an existing cell or a single established area can no longer cover the full structure of the process.",
      left: {
        tag: "Configurable cell or specialist solution",
        title: "When the core of the process is already clearly defined.",
        body: "The starting point is an existing cell architecture or an area such as CNC, injection molding, cobots, material handling, or logistics.",
      },
      right: {
        tag: "Custom-built system",
        title: "When the whole has to be custom-built.",
        body: "The solution is defined by a combination of connected operations, special-purpose stations or tooling, layout, and connections to existing equipment.",
      },
    },
    {
      type: "textOnly",
      id: "sestavni-deli",
      eyebrow: "Parts of the build",
      heading: "We connect only what the actual build requires.",
      body: "That can include a robot, a gripper, a custom-built station, part infeed or outfeed, inspection, and connection to existing equipment. None of these elements on its own defines a custom-built system.",
    },
    {
      type: "relatedSolutions",
      id: "podrocja",
      eyebrow: "Related areas",
      heading: "A specialist area stays a specialist area.",
      body: "A custom-built system can combine elements from these areas, but it doesn't replace them. If one of them already covers the core of the process, that's the right starting point for the solution.",
      linkLabel: "View area",
      items: [
        { title: "CNC machine automation", body: "When the core of the solution is machining, CNC machine tending, and the equipment around it.", routeKey: "solutionCnc" },
        { title: "Injection molding", body: "When the solution is defined by the injection molding machine, the tool, inserts, or the molding cycle.", routeKey: "solutionInjectionMolding" },
        { title: "Collaborative robots", body: "When the main question is whether a cobot is the right technology for a clearly defined operation.", routeKey: "solutionCobots" },
        { title: "Material handling", body: "When the task is mainly gripping, moving, orienting, or handing off a part.", routeKey: "solutionManipulation" },
        { title: "Internal logistics", body: "When the core of the solution is a repeating flow of containers, pallets, or material between stages.", routeKey: "solutionLogistics" },
      ],
    },
    {
      type: "crossSell",
      id: "platforma",
      eyebrow: "A possible starting point",
      heading: "FLEX 25 / 50 can be one of the platforms.",
      body: "In some builds, FLEX 25 / 50 is a configurable starting point. Its applications, options, and technical data are collected on the FLEX 25 / 50 page.",
      right: {
        kind: "image",
        src: "/images/systems/raw/flex-25-50-studio-wide.webp",
        alt: "FLEX 25 / 50 robotic cell",
        reversed: true,
        size: "feature",
        link: { label: "View FLEX 25 / 50", routeKey: "standardCellsFlex2550" },
      },
    },
    {
      type: "proofProject",
      id: "projekt",
      eyebrow: "Completed project",
      heading: "Automatic carton forming and gluing.",
      tag: "Custom-built system for packaging",
      title: "A solution built for a demanding packaging process.",
      body: "Making the packaging was demanding because of different and unpredictable variables, so a custom-built solution was needed for a more stable and controlled workflow.",
      image: { src: "/images/systems/raw/avtomatsko-oblikovanje-in-lepljenje-skatel.png", alt: "Automatic carton forming and gluing" },
      routeKey: "referenceCarton",
      readMoreLabel: "See the custom-built system in practice",
    },
  ],
  kontakt: {
    eyebrow: "Next step",
    heading: "Let's look at what has to work together in your build.",
    body: "To start, we need the sequence of operations, existing equipment, available space, and implementation constraints. From there we assess whether an existing solution covers the process or whether it needs a custom-built system.",
    ctaLabel: "Send an inquiry",
    mailto: "info@flexido.eu",
    imageSrc: "/images/systems/raw/vhodno-izhodna-tracna-proga.png",
    imageAlt: "A connected system of multiple machines and material transport",
    captionEyebrow: "Starting the conversation",
    captionText: "Which sequence of operations can't an existing solution cover?",
    variant: "photo",
  },
};
