import type { SolutionPageContent } from "../types";

/** Faithful structural port of `app/(default)/resitve/namenski-sistemi/page.tsx`. */
export const customSystemsContent: SolutionPageContent = {
  routeKey: "solutionCustomSystems",
  hero: {
    backLabel: "← Vse rešitve",
    eyebrow: "Namenska sestava sistema",
    titleLines: ["Namenski sistemi", "za povezane operacije."],
    subhead:
      "Kadar niti konfigurabilna celica niti eno specialistično področje ne opišeta celotne rešitve, zasnujemo sistem okoli konkretne sestave operacij, postaj in omejitev izvedbe.",
    ctas: [
      { label: "Kdaj je sistem namenski", anchor: "#izbira" },
      { label: "Pogovor o izvedbi", anchor: "#kontakt" },
    ],
    videoSrc: "/video/flexido/hero-home.mp4",
  },
  wikiNav: [
    { id: "sistem", label: "Namenski sistem" },
    { id: "sestava", label: "Kaj ga določa" },
    { id: "izbira", label: "Kdaj je smiseln" },
    { id: "podrocja", label: "Povezana področja" },
    { id: "platforma", label: "Platforma" },
    { id: "projekt", label: "Projekt" },
  ],
  sections: [
    {
      type: "numberedSteps",
      id: "sistem",
      eyebrow: "Namenski sistem",
      heading: "Rešitev presega eno celico ali eno področje.",
      body: "Namenski sistem redko določi en sam gradnik. Sestavljajo ga povezane operacije, namenske postaje in orodja, omejitve izvedbe ter usklajena sestava celote.",
      steps: [
        { label: "Povezane operacije", anchor: "#sestava" },
        { label: "Namenske postaje in orodja", anchor: "#sestava" },
        { label: "Omejitve izvedbe", anchor: "#sestava" },
        { label: "Usklajena sestava", anchor: "#sestava" },
      ],
    },
    {
      type: "capabilityGroups",
      id: "sestava",
      eyebrow: "Namenska sestava",
      heading: "Sistem določa to, kar mora delovati skupaj.",
      body: "Namenski sistem ni katalog gradnikov. Je ena izvedba, v kateri so posamezni deli določeni s konkretnim zaporedjem dela in medsebojnimi omejitvami.",
      layout: "boxed",
      groups: [
        { title: "Povezane operacije", body: "Zaporedje več korakov mora delovati kot ena usklajena izvedba, ne kot samostojna celica z dodatkom." },
        { title: "Namenske postaje in orodja", body: "Proces zahteva postajo, prijem, dovod ali drugo orodje, zasnovano za konkreten kos in potek dela." },
        { title: "Omejitve izvedbe", body: "Razporeditev, obstoječa oprema ali vmesniki določijo arhitekturo sistema že na začetku." },
        { title: "Usklajena sestava", body: "Elementi morajo biti povezani v eno celoto z usklajenim zaporedjem in predajami med njimi." },
      ],
    },
    {
      type: "comparisonSplit",
      id: "izbira",
      eyebrow: "Izbira rešitve",
      heading: "Ne gre le za rešitev po meri.",
      body: "Prilagoditev sama po sebi še ne pomeni namenskega sistema. Ta je smiseln takrat, ko obstoječa celica ali eno uveljavljeno področje ne more prevzeti celotne sestave procesa.",
      left: {
        tag: "Konfigurabilna celica ali specialistična rešitev",
        title: "Ko je jedro procesa že jasno opredeljeno.",
        body: "Izhodišče je obstoječa arhitektura celice ali področje, kot so CNC, brizganje, cobot, manipulacija ali logistika.",
      },
      right: {
        tag: "Namenski sistem",
        title: "Ko je treba namensko sestaviti celoto.",
        body: "Rešitev določi kombinacija povezanih operacij, posebnih postaj ali orodij, razporeditve in povezav z obstoječo opremo.",
      },
    },
    {
      type: "textOnly",
      id: "sestavni-deli",
      eyebrow: "Sestavni deli izvedbe",
      heading: "Povežemo samo tisto, kar zahteva konkretna izvedba.",
      body: "To lahko vključuje robot, prijem, namensko postajo, dovod ali odvod kosov, preverjanje in povezavo z obstoječo opremo. Noben od teh elementov sam po sebi ne določa namenskega sistema.",
    },
    {
      type: "relatedSolutions",
      id: "podrocja",
      eyebrow: "Povezana področja",
      heading: "Specialistično področje ostane specialistično področje.",
      body: "Namenski sistem lahko poveže elemente teh področij, vendar jih ne nadomešča. Če eno od njih opiše jedro procesa, je to pravo izhodišče za rešitev.",
      linkLabel: "Poglej področje",
      items: [
        { title: "CNC avtomatizacija", body: "Kadar je jedro rešitve obdelava, strega CNC strojev in oprema okoli nje.", routeKey: "solutionCnc" },
        { title: "Brizganje plastike", body: "Kadar rešitev določa stroj za brizganje, orodje, inserti ali cikel brizganja.", routeKey: "solutionInjectionMolding" },
        { title: "Kolaborativni roboti", body: "Kadar je glavno vprašanje, ali je cobot primerna tehnologija za jasno operacijo.", routeKey: "solutionCobots" },
        { title: "Manipulacija", body: "Kadar je naloga predvsem prijem, premik, orientacija ali predaja kosa.", routeKey: "solutionManipulation" },
        { title: "Interna logistika", body: "Kadar je jedro rešitve ponavljajoč tok zabojnikov, palet ali materiala med fazami.", routeKey: "solutionLogistics" },
      ],
    },
    {
      type: "crossSell",
      id: "platforma",
      eyebrow: "Možno izhodišče",
      heading: "FLEX 25 / 50 je lahko ena od platform.",
      body: "Pri nekaterih izvedbah je FLEX 25 / 50 konfigurabilno izhodišče. Njegove aplikacije, opcije in tehnični podatki so zbrani na strani FLEX 25 / 50.",
      right: {
        kind: "image",
        src: "/images/systems/raw/flex-25-50-studio-wide.webp",
        alt: "FLEX 25 / 50 robotska celica",
        reversed: true,
        size: "feature",
        link: { label: "Poglej FLEX 25 / 50", routeKey: "standardCellsFlex2550" },
      },
    },
    {
      type: "proofProject",
      id: "projekt",
      eyebrow: "Realiziran projekt",
      heading: "Avtomatsko oblikovanje in lepljenje škatel.",
      tag: "Namenski sistem za pakiranje",
      title: "Rešitev, prilagojena zahtevnemu procesu pakiranja.",
      body: "Izdelava embalaže je bila zahtevna zaradi različnih in nepredvidljivih spremenljivk, zato je bila potrebna namenska rešitev za bolj stabilen in nadzorovan potek dela.",
      image: { src: "/images/systems/raw/avtomatsko-oblikovanje-in-lepljenje-skatel.png", alt: "Avtomatsko oblikovanje in lepljenje škatel" },
      routeKey: "referenceCarton",
      readMoreLabel: "Poglejte namenski sistem v praksi",
    },
  ],
  kontakt: {
    eyebrow: "Naslednji korak",
    heading: "Poglejmo, kaj mora v vaši izvedbi delovati skupaj.",
    body: "Za začetek potrebujemo zaporedje operacij, obstoječo opremo, prostor in omejitve izvedbe. Nato ocenimo, ali proces pokrije obstoječa rešitev ali potrebuje namensko sestavo sistema.",
    ctaLabel: "Pošljite povpraševanje",
    mailto: "info@flexido.eu",
    imageSrc: "/images/systems/raw/vhodno-izhodna-tracna-proga.png",
    imageAlt: "Povezan sistem več strojev in transporta materiala",
    captionEyebrow: "Začetek pogovora",
    captionText: "Katero zaporedje operacij obstoječa rešitev ne more zajeti?",
    variant: "photo",
  },
};
